# Generated by Django 2.1.2 on 2018-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftHandPressure', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rightHandPressure', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('heartRate', models.IntegerField(default=0)),
                ('movement', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=None)),
                ('nodeID', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
