# Generated by Django 2.1.2 on 2018-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='movement',
            field=models.BooleanField(default=False),
        ),
    ]
