# Generated by Django 2.1.2 on 2018-11-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_sensordata_movement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='celcius',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='pressure',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='avgHR',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='leftAvg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='leftMax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='leftMin',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='rightAvg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='rightMax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='rightMin',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
