# Generated by Django 2.1.2 on 2018-11-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20181122_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='avgHR',
            new_name='heartRate',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='leftAvg',
            new_name='leftHandPressure',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='rightAvg',
            new_name='rightHandPressure',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='leftMax',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='leftMin',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='rightMax',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='rightMin',
        ),
    ]
