# Generated by Django 2.1.2 on 2018-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20181124_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='heartRate',
            field=models.IntegerField(default=0),
        ),
    ]
